name: 'My #1 GRID Site'
favicon: null
layout_spectrum: 0.17104654875583947
typography_spectrum: 0.92066246480681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4440256794914603
  lightness: 0.8527996784541756
  saturation: 0.07842727773822844
  rhythmicContrast: 0.055582660250365734
purpose: []
